version: '3'

services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      - redis
    networks:
      - my_network
    container_name: apn107_socket

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - my_network
    container_name: redis_container

networks:
  my_network:
    driver: bridge
